version: '3.8'

services:
  app:
    build: .
    name: express-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=8807f384d5f5cde1187132d957bca1bfe91705ffb92dd9fe611e80fbcc3b1e06
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_SECRET=ac0473b3dd7356b79642f8b711647baa1facd4687d8185de2df23e96eabd89ee
      - JWT_REFRESH_EXPIRES_IN=1d
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=mydb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis@pass
      - REDIS_DB=0
      - REDIS_TTL=86400
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:17.5
    name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    name: redis-db
    ports:
      - '6379:6379'
    command: redis-server --requirepass redis@pass
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
